name: Dog Breeds

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    outputs:
      output1: ${{ steps.run1.outputs.test }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # - name: Run tests
    #   run: |
    #     pytest

    - name: Lint code
      run: |
        pip install flake8
        flake8 src/ --max-line-length=200
    
    - name: Run main script
      id: run1
      run: |
        python src/main.py >> "$GITHUB_OUTPUT"
  
  deploy:
    runs-on: ubuntu-latest
    
    needs: build
    
    steps:
      - env:
          OUTPUT1: ${{needs.build.outputs.output1}}
        name: Yoda
        run: echo "$OUTPUT1"
